### ISSUE TITLE
undefined

### ISSUE THREAD

**Issue by skykep** [hirokiht/ethernet-ip-cip#2]
No issues when using the ethernet-ip package, but when trying this ethernet-ip-cip, I get this:

`(node:5650) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'build' of undefined
    at Controller.write_cip (/home/phuz/node_modules/ethernet-ip-cip/src/controller/index.js:146:33)
    at Controller.readControllerProps (/home/phuz/node_modules/ethernet-ip-cip/src/controller/index.js:171:10)
    at Controller.connect (/home/phuz/node_modules/ethernet-ip-cip/src/controller/index.js:125:16)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:5650) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:5650) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
^C
`

**Comment by alishefaee** [comment]
@skykep Did you solve this problem?
